sudo: false # use new container
language: c

branches:
  except: /^(gh-pages|v[0-9]\..*)/

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      # xrdp
      - libpam0g-dev
      - libjpeg-dev
      - libfuse-dev
      - libmp3lame-dev
      - libx11-dev
      - libxrandr-dev
      - libpixman-dev
      - nasm
      # x11rdp
      #- flex
      #- bison
      #- libxml2-dev
      #- intltool
      #- xsltproc
      #- xutils-dev
      #- python-libxml2
      #- g++
      #- xutils

script:
  # disable librfxcodec as no remotefx for v0.9.1 release
  #- (cd librfxcodec && ./bootstrap && ./configure && make)
  - (./bootstrap && ./configure --enable-ipv6 --enable-jpeg --enable-fuse --enable-mp3lame --enable-pixman && make && make distcheck)
  # disable x11rdp build as it takes long time and it is to be deprecated
  #- (cd xorg/X11R7.6 && ./buildx.sh default)
